name: Rust

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

# env:
#   CARGO_TERM_COLOR: always

jobs:
  nowasm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: nowasm-build
        run: cargo build
  wasm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rust-src
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'
      - name: wasm-build
        run: ./wasm_build.sh
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: fmt
        run: cargo fmt
